---
Title: HW1
Author: Liam O'Neill
Date: Aug-31-2022
output: GitHug
---
##R

##Small Stuff
```{r}
x <- 1:50
w <- 1 + sqrt(x)/2
example1 <- data.frame(x=x, y= x + rnorm(x)*w)
attach(example1)
```

```{r}
fm <- lm(y ~ x)
summary(fm)
```

```{r}
lrf <- lowess(x, y)
plot(x, y)
lines(x, lrf$y)
abline(0, 1, lty=3)
abline(coef(fm))
```

```{r}
detach()
```

##With Some Data

```{r}
getwd()
```
```{r}
load("Household_Pulse_data.RData")
#glimpse(acs2017_ny) try this later
Household_Pulse_data[1:10,1:7]
```
```{r}
attach(Household_Pulse_data)
```
```{r}
summary(Household_Pulse_data)
```

##Simple Stats

```{r}
summary(TBIRTH_YEAR[GENID_DESCRIBE == "female"])
# here i want to find average ages of men and women
mean(TBIRTH_YEAR[GENID_DESCRIBE == "female"])
sd(TBIRTH_YEAR[GENID_DESCRIBE == "female"])
```
```{r}
summary(TBIRTH_YEAR[GENID_DESCRIBE == "male"])
mean(TBIRTH_YEAR[GENID_DESCRIBE == "male"])
sd(TBIRTH_YEAR[GENID_DESCRIBE == "male"])
```
```{r}
summary(TBIRTH_YEAR[GENID_DESCRIBE == "transgender"])
```
```{r}
summary(TBIRTH_YEAR[GENID_DESCRIBE == "other"])
```
```{r}
summary(TBIRTH_YEAR[GENID_DESCRIBE == "NA"])
```